#!/bin/sh
### BEGIN INIT INFO
# Provides:          dhcpcd
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DHCP Client Daemon
# Description:       Provides DHCP configuration for network interfaces.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="DHCP client"
NAME="dhcpcd"
DAEMON="/sbin/dhcpcd"
PIDFILE="/var/run/dhcpcd.pid"

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --start --quiet --oknodo --pidfile "$PIDFILE" --exec "$DAEMON"
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE" --exec "$DAEMON"
    log_end_msg $?
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
    exit 3
    ;;
esac
