#!/bin/bash

### BEGIN INIT INFO
# Provides:		dtlogin
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start:	2 5
# Default-Stop:		0 1 3 6
# Short-Description:	dtlogin service
### END INIT INFO

DAEMON="/usr/dt/bin/dtlogin"
PIDFILE="/var/run/dtlogin.pid"

case "$1" in
	start)
		echo "Starting dtlogin..."
		start-stop-daemon --start --background --pidfile "$PIDFILE" --make-pidfile --exec "$DAEMON"
		;;
	stop)
		echo "Stopping dtlogin..."
		start-stop-daemon --stop --pidfile "$PIDFILE"
        	rm -f "$PIDFILE"
        	;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		if [ -f "$PIDFILE" ]; then
			echo "dtlogin is running (PID $(cat $PIDFILE))."
		else
			echo "dtlogin is not running."
		fi
		;;
	*)
		echo "Usage: /etc/init.d/dtlogin {start|stop|restart|status}"
		exit 1
		;;
	esac

exit 0
