#!/bin/bash

### BEGIN INIT INFO
# Provides:		windscribe-helper
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Helper for Windscribe
### END INIT INFO

DAEMON="/opt/windscribe/helper"
PIDFILE="/var/run/windscribe-helper.pid"

case "$1" in
	start)
		echo "Starting windscribe-helper..."
		start-stop-daemon --start --background --pidfile "$PIDFILE" --make-pidfile --exec "$DAEMON"
		;;
	stop)
		echo "Stopping windscribe-helper..."
		start-stop-daemon --stop --pidfile "$PIDFILE"
        	rm -f "$PIDFILE"
        	;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		if [ -f "$PIDFILE" ]; then
			echo "windscribe-helper is running (PID $(cat $PIDFILE))."
		else
			echo "windscribe-helper is not running."
		fi
		;;
	*)
		echo "Usage: /etc/init.d/windscribe-helper {start|stop|restart|status}"
		exit 1
		;;
	esac

exit 0
