#!/bin/sh
### BEGIN INIT INFO
# Provides:          wpa_supplicant
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       WPA Supplicant Daemon
### END INIT INFO

INTERFACE="wlan0"
CONFIG="/etc/wpa_supplicant/wpa_supplicant.conf"
PIDFILE="/var/run/wpa_supplicant-$INTERFACE.pid"
BIN="/sbin/wpa_supplicant"

case "$1" in
    start)
        echo "Starting wpa_supplicant..."
        $BIN -B -i $INTERFACE -c $CONFIG -P $PIDFILE
        ;;
    stop)
        echo "Stopping wpa_supplicant..."
        kill $(cat $PIDFILE)
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
